from . import drbb_picking_time_category
from . import drbb_picking_priority_rule
from . import stock_move
from . import product_template
from . import drbb_product_brand
from . import loyalty_program
from . import stock_picking_batch
from . import stock_move_line
from . import planning_slot
from . import stock_location
from . import stock_picking_type
from . import stock_storage_category
from . import drbb_location_tag
from . import drbb_product_stage
from . import product_category
from . import package_zone
from . import stock_picking
from . import stock_quant_package
from . import drbb_product_abc_class
from . import drbb_product_brand_type
from . import drbb_product_item_role
from . import drbb_product_item_status
from . import drbb_product_item_type
from . import drbb_product_language
from . import drbb_product_quality_label
from . import drbb_product_collection
from . import drbb_product_subcollection
from . import drbb_product_type
from . import drbb_product_other_color
from . import drbb_product_cross_sell
from . import drbb_product_other_color_variant
from . import drbb_product_cross_sell_variant
from . import drbb_location_group
from . import res_users
from . import product_translation
from . import product_translation_item
from . import translation_item
from . import stock_warehouse
from . import product_product
from . import drbb_promotion_exclude_label
from . import drbb_promotion_website_label
from . import stock_quant
from . import drbb_product_inventory_section
from . import res_partner
from . import stock_warehouse_orderpoint
from . import drbb_stock_picking_label
from . import res_company
from . import res_config_settings
