{
    "name": "Dreambaby Inventory",
    "summary": "Dreambaby Inventory",
    "description": "Dreambaby Inventory",
    "author": "Konu",
    "website": "https://www.konu.be",
    "license": "AGPL-3",
    "category": "Extension",
    "version": "18.0.0.4",
    "depends": ["stock", "product", "loyalty", "sale_stock", "stock_picking_batch", "stock_barcode",
                "stock_barcode_picking_batch", "web_gantt", "planning", "spreadsheet_dashboard", 'mrp', 'uom',
                'point_of_sale', "delivery_stock_picking_batch", "konu_eu_price_compliance", "purchase",
                # "drbb_replenish_to_order_optimize"
            ],
    "sequence": 0,
    "data": [
        "security/ir.model.access.csv",
        "data/mail_data.xml",
        "data/package_zone_data.xml",
        "wizard/base_language_install_views.xml",
        "wizard/choose_pack_package_views.xml",
        "wizard/drbb_batch_split_wizard_views.xml",
        "views/drbb_picking_priority_rule_views.xml",
        "views/drbb_picking_time_category_views.xml",
        "views/stock_move_views.xml",
        "views/product_template_views.xml",
        "views/product_category_views.xml",
        "views/drbb_product_brand_views.xml",
        "views/loyalty_program_views.xml",
        "views/stock_picking_batch_views.xml",
        "views/drbb_location_tag_views.xml",
        "views/drbb_product_stage_views.xml",
        "views/drbb_product_abc_class_views.xml",
        "views/drbb_product_brand_type_views.xml",
        "views/drbb_product_item_role_views.xml",
        "views/drbb_product_item_status_views.xml",
        "views/drbb_product_item_type_views.xml",
        "views/drbb_product_language_views.xml",
        "views/drbb_product_quality_labels_views.xml",
        "views/drbb_location_group_views.xml",
        "views/drbb_promotion_exclude_label_views.xml",
        "views/drbb_promotion_website_label_views.xml",
        "views/drbb_stock_picking_label_views.xml",
        "views/stock_move_line_views.xml",
        "views/planning_slot_views.xml",
        "views/stock_location_views.xml",
        "views/stock_picking_type_views.xml",
        "views/stock_storage_category_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_quant_package_views.xml",
        "views/stock_warehouse_views.xml",
        "views/product_packaging_views.xml",
        "views/product_pricelist_item_views.xml",
        "views/product_translation_item_views.xml",
        "views/stock_barcode_views.xml",
        "views/translation_term_views.xml",
        "views/drbb_product_inventory_section_views.xml",
        "views/drbb_inventory_menus.xml",
        "views/product_product_views.xml",
        "views/stock_scrap_views.xml",
        "views/stock_quant_views.xml",
        "views/res_partner_views.xml",
        "reports/product_discount_zpl_label.xml",
        "reports/package_templates.xml",
        "reports/stock_picking_batch_report_views.xml",
        "reports/report_picking_batch.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'drbb_inventory/static/src/models/barcode_picking_batch_model.js',
            'drbb_inventory/static/src/models/barcode_model.js',
            'drbb_inventory/static/src/models/barcode_picking_model.js',
            'drbb_inventory/static/src/components/main.js',
            'drbb_inventory/static/src/components/missing_moves_dialog.js',
            'drbb_inventory/static/src/**/*.xml',
        ],
        'web.assets_backend_lazy': [
            'drbb_inventory/static/src/views/drbb_inventory_gantt/drbb_inventory_gantt_row_progress_bar.xml',
            'drbb_inventory/static/src/views/drbb_inventory_gantt/drbb_inventory_gantt_row_progress_bar.js',
        ],
    },
    "demo": [
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
